theme = "carbon"

[editor]
auto-completion = true
completion-timeout = 5
completion-trigger-len = 1
preview-completion-insert = true
completion-replace = true

# [editor.auto-save.after-delay]
# enable = true
# timeout = 300

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
j = { k = "normal_mode"}
