general {
    lock_cmd = noctalia msg session lock
    before_sleep_cmd = loginctl lock-session
    inhibit_sleep = 3
}

listener {
    timeout = 1800
    on-timeout = loginctl lock-session
}

listener {
    timeout = 1830
    on-timeout = hyprctl dispatch 'hl.dsp.dpms("off")'
    on-resume = hyprctl dispatch 'hl.dsp.dpms("on")'
}
