general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    color = rgba(1a1a1aee)
}

input-field {
    size = 200, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.3
    outer_color = rgba(89b4faff)
    inner_color = rgba(1e1e2eff)
    font_color = rgba(cdd6f4ff)
    placeholder_text = Password...
    fail_text = $FAIL
    position = 0, -20
    halign = center
    valign = center
}

label {
    text = $TIME
    color = rgba(cdd6f4ff)
    font_size = 32
    position = 0, 80
    halign = center
    valign = center
}
