
# dracula-theme.conf

dark_grey="#3A3C48"
white="#f8f8f2"
purple="#bd93f9"
pink="#ff79c6"
green="#50fa7b"
light_gray="#7A89B3"
medium_gray="#44475a"

# Set the status bar position
set -g status-position top

set -g status-left-length 200

# Center the window list
set -g status-justify centre

# Global status bar background (Dracula Background)
set -g status-style "bg=#282a36"

# Left side: Session name (Dracula Purple)
set -g status-left "#[fg=${medium_gray},bg=default]#[bg=${medium_gray}]#{?client_prefix,#[fg=${purple}],#[fg=${green}]}#[fg=${white},bold] #S#[fg=${medium_gray},bg=default]"



# Right side: Date and Time (Dracula Foreground)
set -g status-right "#[fg=${medium_gray},bg=default]#[fg=${white},bg=${medium_gray}]󰃮 %Y-%m-%d 󱑒 %H:%M#[fg=${medium_gray},bg=default]"
set -g status-right-length 200


# Active window tab (Dracula Pink)
set -g window-status-current-format "#[fg=${pink},bg=default] #[underscore]#I:#W"

# Inactive window tabs (Dracula Comment/Muted)
set -g window-status-format "#[fg=${light_gray},bg=default] #I:#W"
set -g window-status-last-style "fg=${light_gray},bg=default"

# Command prompt styling
set -g message-command-style "bg=${medium_gray},fg=${white}"
set -g message-style "bg=${medium_gray},fg=${white}"


# Copy mode highlighting / Selection
set -g mode-style "bg=${medium_gray},fg=${white}"

# Pane borders
set -g pane-active-border-style "fg=${purple},bg=default"
set -g pane-border-style "fg=${medium_gray},bg=default"

