# Set the status bar position
set -g status-position top

# Left side: Session name
set -g status-left "#[fg=#A3BE8C,bold,bg=#3B4252] #S"
set -g status-left-length 200

# Right side: Date and Time
set -g status-right "#[fg=#D8DEE9,bg=#3B4252] 󰃮 %Y-%m-%d 󱑒 %H:%M"
set -g status-right-length 200

# Center the window list
set -g status-justify centre

# Global status bar background
set -g status-style "bg=#3B4252"

# Active window tab
set -g window-status-current-format "#[fg=#88C0D0,bg=default]  #I:#W"

# Inactive window tabs
set -g window-status-format "#[fg=#D8DEE9,bg=default] #I:#W"
set -g window-status-last-style "fg=#D8DEE9,bg=default"

# Command prompt styling
set -g message-command-style "bg=default,fg=#D8DEE9"
set -g message-style "bg=default,fg=#D8DEE9"

# Copy mode highlighting (Selection)
set -g mode-style "bg=#81A1C1,fg=#3B4252"

# Pane borders
set -g pane-active-border-style "fg=#abb2bf,bg=default"
set -g pane-border-style "fg=brightblack,bg=default"
